// * Collection reducer action types
const CREATE_FOLDER = "CREATE_FOLDER";
const EDIT_FOLDER = "EDIT_FOLDER";
const CREATE_TODO = "CREATE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const SET_FILTER = "SET_FILTER";
const RESET_FILTER = "RESET_FILTER";
const REFRESH_TODOS_AFTER_DROP = "REFRESH_TODOS_AFTER_DROP";
const REMOVE_FOLDER = "DELETE_FOLDER";
const SET_CURR_FOLDER_ID = "SET_CURR_FOLDER";
const SET_FOLDERS = "SET_FOLDERS";
const SET_FOLDERS_LOADING = "SET_FOLDERS_LOADING";
const RESET_FOLDERS_LOADING = "RESET_FOLDERS_LOADING";
const SET_FOLDER_AFTER_ACCEPTING = "SET_FOLDER_AFTER_ACCEPTING";
const REFRESH_FOLDER = "REFRESH_FOLDER";
const SET_CREATING_FOLDER = "SET_CREATING_FOLDER";
const RESET_CREATING_FOLDER = "RESET_CREATING_FOLDER";

// * Invitation reducer action types
const SET_INVITATIONS_LOADING = "SET_INVITATIONS_LOADING";
const RESET_INVITATIONS_LOADING = "RESET_INVITATIONS_LOADING";
const INIT_INVITATIONS = "INIT_INVITATIONS";
const SEND_INVITATION = "SEND_INVITATION";
const ACCEPT_INVITATION = "ACCEPT_INVITATION";
const CANCEL_INVITATION = "CANCEL_INVITATION";
const DECLINE_INVITATION = "DECLINE_INVITATION";

// * UI REDucer action types
const SET_NOTIFICATION = "SET_NOTIFICATION";
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

// * User Reducer action types
const SET_USER = "SET_USER";
const INIT_USER = "INIT_USER";
const INIT_USER_FAILED = "INIT_USER_FAILED";
const REMOVE_USER = "RESET_USER";

export default {
  CREATE_FOLDER,
  EDIT_FOLDER,
  CREATE_TODO,
  TOGGLE_TODO,
  REMOVE_TODO,
  SET_FILTER,
  RESET_FILTER,
  REFRESH_TODOS_AFTER_DROP,
  REMOVE_FOLDER,
  SET_CURR_FOLDER_ID,
  SET_FOLDERS,
  SET_FOLDERS_LOADING,
  RESET_FOLDERS_LOADING,
  SET_FOLDER_AFTER_ACCEPTING,
  REFRESH_FOLDER,
  SET_CREATING_FOLDER,
  RESET_CREATING_FOLDER,
  SET_INVITATIONS_LOADING,
  RESET_INVITATIONS_LOADING,
  INIT_INVITATIONS,
  SEND_INVITATION,
  ACCEPT_INVITATION,
  CANCEL_INVITATION,
  DECLINE_INVITATION,
  SET_NOTIFICATION,
  REMOVE_NOTIFICATION,
  SET_USER,
  INIT_USER,
  INIT_USER_FAILED,
  REMOVE_USER,
};
